// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: skoXdD1kXUMVpincrRuSob
// Component: GFQy7IrqN9Eh
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: skoXdD1kXUMVpincrRuSob/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: GFQy7IrqN9Eh/css
import MobileSignalIcon from "./icons/PlasmicIcon__MobileSignal"; // plasmic-import: UaNsfUdH8b/icon
import WifiIcon from "./icons/PlasmicIcon__Wifi"; // plasmic-import: -YZCYsSwNQ/icon
import BatteryIcon from "./icons/PlasmicIcon__Battery"; // plasmic-import: qw2Y0oUvkP/icon
import Ellipse5Icon from "./icons/PlasmicIcon__Ellipse5"; // plasmic-import: F3snXgWF1y0/icon
import LeftActionableIcon from "./icons/PlasmicIcon__LeftActionable"; // plasmic-import: 8hMosncB-3Z/icon
import RightActionableIcon from "./icons/PlasmicIcon__RightActionable"; // plasmic-import: wWD8P5j5pHb/icon
import RightActionable2Icon from "./icons/PlasmicIcon__RightActionable2"; // plasmic-import: bEJ1h7omIOE/icon
import Line5Icon from "./icons/PlasmicIcon__Line5"; // plasmic-import: 68gnK2psoEx/icon
import EllipseIcon from "./icons/PlasmicIcon__Ellipse"; // plasmic-import: 6T7iYc4Y873/icon
import Group2Icon from "./icons/PlasmicIcon__Group2"; // plasmic-import: zdiIVD2LBH8/icon
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: L1HVn3C7ZSg/icon
import Group4Icon from "./icons/PlasmicIcon__Group4"; // plasmic-import: TrYbCCFwiiA/icon
import Group5Icon from "./icons/PlasmicIcon__Group5"; // plasmic-import: xvHj_Fev2ku/icon
import Group6Icon from "./icons/PlasmicIcon__Group6"; // plasmic-import: gO-2C1mVZ2L/icon
import Line14Icon from "./icons/PlasmicIcon__Line14"; // plasmic-import: q5G7mDR9Y_o/icon
import Rectangle35Icon from "./icons/PlasmicIcon__Rectangle35"; // plasmic-import: aASMKQX9Wqq/icon
import IconOutlinelightningBoltIcon from "./icons/PlasmicIcon__IconOutlinelightningBolt"; // plasmic-import: hOyySJmZ8Jk/icon
import Ellipse4Icon from "./icons/PlasmicIcon__Ellipse4"; // plasmic-import: t2FU-EY4u/icon
import IconOutlinesparklesIcon from "./icons/PlasmicIcon__IconOutlinesparkles"; // plasmic-import: ZCtI7nunO1/icon
import IconSolidsunIcon from "./icons/PlasmicIcon__IconSolidsun"; // plasmic-import: 5KCZrpIEwSV/icon
import IconSolidlightningBoltIcon from "./icons/PlasmicIcon__IconSolidlightningBolt"; // plasmic-import: roK2mA-z8i8/icon
import Line18Icon from "./icons/PlasmicIcon__Line18"; // plasmic-import: T5jiXwevxob/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style global jsx>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__nBcxw
            )}
          >
            {"Welcome to your first page."}
          </div>

          <div
            data-plasmic-name={"dashboardSiteDetail"}
            data-plasmic-override={overrides.dashboardSiteDetail}
            className={classNames(defaultcss.all, sty.dashboardSiteDetail)}
          >
            <div
              data-plasmic-name={"nativeStatusBar"}
              data-plasmic-override={overrides.nativeStatusBar}
              className={classNames(defaultcss.all, sty.nativeStatusBar)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__miuC
                )}
              >
                {"9:41"}
              </div>

              <MobileSignalIcon
                className={classNames(defaultcss.all, sty.svg___8Nzuy)}
                role={"img"}
              />

              <WifiIcon
                className={classNames(defaultcss.all, sty.svg__ydnbn)}
                role={"img"}
              />

              <div
                data-plasmic-name={"battery"}
                data-plasmic-override={overrides.battery}
                className={classNames(defaultcss.all, sty.battery)}
              >
                <BatteryIcon
                  className={classNames(defaultcss.all, sty.svg__oTci)}
                  role={"img"}
                />
              </div>
            </div>

            {false ? (
              <div
                data-plasmic-name={"group439"}
                data-plasmic-override={overrides.group439}
                className={classNames(defaultcss.all, sty.group439)}
              >
                <div
                  data-plasmic-name={"rectangle23"}
                  data-plasmic-override={overrides.rectangle23}
                  className={classNames(defaultcss.all, sty.rectangle23)}
                />

                <div
                  data-plasmic-name={"image"}
                  data-plasmic-override={overrides.image}
                  className={classNames(defaultcss.all, sty.image)}
                />

                {false ? (
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__lOwNy)}
                    role={"img"}
                    src={"/plasmic/blank_project/images/ellipse2.svg"}
                  />
                ) : null}
              </div>
            ) : null}

            <div
              data-plasmic-name={"rectangle24"}
              data-plasmic-override={overrides.rectangle24}
              className={classNames(defaultcss.all, sty.rectangle24)}
            />

            <div
              data-plasmic-name={"barsNavBarsStandard"}
              data-plasmic-override={overrides.barsNavBarsStandard}
              className={classNames(defaultcss.all, sty.barsNavBarsStandard)}
            >
              <div
                data-plasmic-name={"group505"}
                data-plasmic-override={overrides.group505}
                className={classNames(defaultcss.all, sty.group505)}
              >
                <div
                  data-plasmic-name={"title"}
                  data-plasmic-override={overrides.title}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.title
                  )}
                >
                  {"Hoa Nang Solar Farm"}
                </div>

                <Ellipse5Icon
                  className={classNames(defaultcss.all, sty.svg__jLgnI)}
                  role={"img"}
                />
              </div>

              <LeftActionableIcon
                className={classNames(defaultcss.all, sty.svg__vPk58)}
                role={"img"}
              />

              {false ? (
                <RightActionableIcon
                  className={classNames(defaultcss.all, sty.svg__lfh5O)}
                  role={"img"}
                />
              ) : null}
              {false ? (
                <RightActionable2Icon
                  className={classNames(defaultcss.all, sty.svg__zRg6E)}
                  role={"img"}
                />
              ) : null}
            </div>

            <Line5Icon
              className={classNames(defaultcss.all, sty.svg__mjScg)}
              role={"img"}
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame495"}
              data-plasmic-override={overrides.frame495}
              hasGap={true}
              className={classNames(defaultcss.all, sty.frame495)}
            >
              <div
                data-plasmic-name={"group454"}
                data-plasmic-override={overrides.group454}
                className={classNames(defaultcss.all, sty.group454)}
              >
                <div
                  data-plasmic-name={"rectangle5"}
                  data-plasmic-override={overrides.rectangle5}
                  className={classNames(defaultcss.all, sty.rectangle5)}
                />

                <div
                  data-plasmic-name={"frame509"}
                  data-plasmic-override={overrides.frame509}
                  className={classNames(defaultcss.all, sty.frame509)}
                >
                  <div
                    data-plasmic-name={"maskGroup"}
                    data-plasmic-override={overrides.maskGroup}
                    className={classNames(defaultcss.all, sty.maskGroup)}
                  >
                    <div
                      data-plasmic-name={"rectangle4"}
                      data-plasmic-override={overrides.rectangle4}
                      className={classNames(defaultcss.all, sty.rectangle4)}
                    />

                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img___9VQlc)}
                      role={"img"}
                      src={"/plasmic/blank_project/images/group.svg"}
                    />

                    <div
                      data-plasmic-name={"group"}
                      data-plasmic-override={overrides.group}
                      className={classNames(defaultcss.all, sty.group)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame9"}
                        data-plasmic-override={overrides.frame9}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.frame9)}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__m58Hp
                          )}
                        >
                          {"32"}
                        </div>

                        <EllipseIcon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___4XzMe
                          )}
                          role={"img"}
                        />
                      </p.Stack>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"sun1"}
                    data-plasmic-override={overrides.sun1}
                    className={classNames(defaultcss.all, sty.sun1)}
                  >
                    <div
                      data-plasmic-name={"group2"}
                      data-plasmic-override={overrides.group2}
                      className={classNames(defaultcss.all, sty.group2)}
                    >
                      <Group2Icon
                        className={classNames(defaultcss.all, sty.svg__aum6W)}
                        role={"img"}
                      />
                    </div>

                    <div
                      data-plasmic-name={"group3"}
                      data-plasmic-override={overrides.group3}
                      className={classNames(defaultcss.all, sty.group3)}
                    >
                      <Group3Icon
                        className={classNames(defaultcss.all, sty.svg__mEaP)}
                        role={"img"}
                      />
                    </div>

                    <div
                      data-plasmic-name={"group4"}
                      data-plasmic-override={overrides.group4}
                      className={classNames(defaultcss.all, sty.group4)}
                    >
                      <Group4Icon
                        className={classNames(defaultcss.all, sty.svg__pmnDr)}
                        role={"img"}
                      />
                    </div>

                    <div
                      data-plasmic-name={"group5"}
                      data-plasmic-override={overrides.group5}
                      className={classNames(defaultcss.all, sty.group5)}
                    >
                      <Group5Icon
                        className={classNames(defaultcss.all, sty.svg__mkzv)}
                        role={"img"}
                      />
                    </div>

                    <div
                      data-plasmic-name={"group6"}
                      data-plasmic-override={overrides.group6}
                      className={classNames(defaultcss.all, sty.group6)}
                    >
                      <Group2Icon
                        className={classNames(defaultcss.all, sty.svg__ykrGx)}
                        role={"img"}
                      />
                    </div>

                    <div
                      data-plasmic-name={"group7"}
                      data-plasmic-override={overrides.group7}
                      className={classNames(defaultcss.all, sty.group7)}
                    >
                      <Group3Icon
                        className={classNames(defaultcss.all, sty.svg__xWYnk)}
                        role={"img"}
                      />
                    </div>

                    <div
                      data-plasmic-name={"group8"}
                      data-plasmic-override={overrides.group8}
                      className={classNames(defaultcss.all, sty.group8)}
                    >
                      <Group4Icon
                        className={classNames(defaultcss.all, sty.svg__tBb4O)}
                        role={"img"}
                      />
                    </div>

                    <div
                      data-plasmic-name={"group9"}
                      data-plasmic-override={overrides.group9}
                      className={classNames(defaultcss.all, sty.group9)}
                    >
                      <Group5Icon
                        className={classNames(defaultcss.all, sty.svg__lbkdd)}
                        role={"img"}
                      />
                    </div>

                    <div
                      data-plasmic-name={"group10"}
                      data-plasmic-override={overrides.group10}
                      className={classNames(defaultcss.all, sty.group10)}
                    >
                      <Group6Icon
                        className={classNames(defaultcss.all, sty.svg___9XWd)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>

                <div
                  data-plasmic-name={"group453"}
                  data-plasmic-override={overrides.group453}
                  className={classNames(defaultcss.all, sty.group453)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame497"}
                    data-plasmic-override={overrides.frame497}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.frame497)}
                  >
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__eEelf)}
                      role={"img"}
                      src={
                        "/plasmic/blank_project/images/wirelessCharging1.svg"
                      }
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__pb9H3
                      )}
                    >
                      {"Active Power"}
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame2"}
                    data-plasmic-override={overrides.frame2}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.frame2)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__bYVor
                      )}
                    >
                      {"287"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box___24BdA
                      )}
                    >
                      {"W"}
                    </div>
                  </p.Stack>
                </div>
              </div>

              <div
                data-plasmic-name={"group455"}
                data-plasmic-override={overrides.group455}
                className={classNames(defaultcss.all, sty.group455)}
              >
                <div
                  data-plasmic-name={"rectangle25"}
                  data-plasmic-override={overrides.rectangle25}
                  className={classNames(defaultcss.all, sty.rectangle25)}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__xjy2Z
                  )}
                >
                  {"Production"}
                </div>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame453"}
                  data-plasmic-override={overrides.frame453}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.frame453)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame450"}
                    data-plasmic-override={overrides.frame450}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.frame450)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__d1D0N
                      )}
                    >
                      {"Today"}
                    </div>

                    <div
                      data-plasmic-name={"frame451"}
                      data-plasmic-override={overrides.frame451}
                      className={classNames(defaultcss.all, sty.frame451)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__poS18
                        )}
                      >
                        {"2827"}
                      </div>

                      <div
                        data-plasmic-name={"wh"}
                        data-plasmic-override={overrides.wh}
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.wh
                        )}
                      >
                        {" Wh"}
                      </div>
                    </div>
                  </p.Stack>

                  <div className={classNames(defaultcss.all, sty.box__mvXvB)}>
                    <Line14Icon
                      className={classNames(defaultcss.all, sty.svg___0QqDg)}
                      role={"img"}
                    />
                  </div>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame452"}
                    data-plasmic-override={overrides.frame452}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.frame452)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__eGtWs
                      )}
                    >
                      {"This month"}
                    </div>

                    <div
                      data-plasmic-name={"frame454"}
                      data-plasmic-override={overrides.frame454}
                      className={classNames(defaultcss.all, sty.frame454)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__sBnDf
                        )}
                      >
                        {"2168.68"}
                      </div>

                      <div
                        data-plasmic-name={"kWh"}
                        data-plasmic-override={overrides.kWh}
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.kWh
                        )}
                      >
                        {" kWh"}
                      </div>
                    </div>
                  </p.Stack>

                  <div className={classNames(defaultcss.all, sty.box__veTSu)}>
                    <Line14Icon
                      className={classNames(defaultcss.all, sty.svg__oUiOu)}
                      role={"img"}
                    />
                  </div>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame455"}
                    data-plasmic-override={overrides.frame455}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.frame455)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__ttz6T
                      )}
                    >
                      {"This year"}
                    </div>

                    <div
                      data-plasmic-name={"frame456"}
                      data-plasmic-override={overrides.frame456}
                      className={classNames(defaultcss.all, sty.frame456)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__pi8Oz
                        )}
                      >
                        {"33.13"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__mQNxL
                        )}
                      >
                        {"MWh"}
                      </div>
                    </div>
                  </p.Stack>
                </p.Stack>
              </div>

              <div
                data-plasmic-name={"group503"}
                data-plasmic-override={overrides.group503}
                className={classNames(defaultcss.all, sty.group503)}
              >
                <div
                  data-plasmic-name={"rectangle37"}
                  data-plasmic-override={overrides.rectangle37}
                  className={classNames(defaultcss.all, sty.rectangle37)}
                />

                <div
                  data-plasmic-name={"rectangle38"}
                  data-plasmic-override={overrides.rectangle38}
                  className={classNames(defaultcss.all, sty.rectangle38)}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__mGpMm
                  )}
                >
                  {"Data"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___57JOa
                  )}
                >
                  {"Device"}
                </div>
              </div>

              <div
                data-plasmic-name={"frame10"}
                data-plasmic-override={overrides.frame10}
                className={classNames(defaultcss.all, sty.frame10)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame7"}
                  data-plasmic-override={overrides.frame7}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.frame7)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ydtUl
                    )}
                  >
                    {"Last 7 days (05/06 - 12/06)"}
                  </div>
                </p.Stack>
              </div>

              <div
                data-plasmic-name={"group494"}
                data-plasmic-override={overrides.group494}
                className={classNames(defaultcss.all, sty.group494)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame498"}
                  data-plasmic-override={overrides.frame498}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.frame498)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame474"}
                    data-plasmic-override={overrides.frame474}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.frame474)}
                  >
                    <div
                      data-plasmic-name={"group471"}
                      data-plasmic-override={overrides.group471}
                      className={classNames(defaultcss.all, sty.group471)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame499"}
                        data-plasmic-override={overrides.frame499}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.frame499)}
                      >
                        <div
                          data-plasmic-name={"group467"}
                          data-plasmic-override={overrides.group467}
                          className={classNames(defaultcss.all, sty.group467)}
                        >
                          <div
                            data-plasmic-name={"rectangle34"}
                            data-plasmic-override={overrides.rectangle34}
                            className={classNames(
                              defaultcss.all,
                              sty.rectangle34
                            )}
                          />

                          <div
                            data-plasmic-name={"group498"}
                            data-plasmic-override={overrides.group498}
                            className={classNames(defaultcss.all, sty.group498)}
                          >
                            <div
                              data-plasmic-name={"group497"}
                              data-plasmic-override={overrides.group497}
                              className={classNames(
                                defaultcss.all,
                                sty.group497
                              )}
                            >
                              <Rectangle35Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___72DnY
                                )}
                                role={"img"}
                              />

                              <div
                                data-plasmic-name={"group465"}
                                data-plasmic-override={overrides.group465}
                                className={classNames(
                                  defaultcss.all,
                                  sty.group465
                                )}
                              >
                                <IconOutlinelightningBoltIcon
                                  className={classNames(
                                    defaultcss.all,
                                    sty.svg__krw01
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>

                            <div
                              data-plasmic-name={"group466"}
                              data-plasmic-override={overrides.group466}
                              className={classNames(
                                defaultcss.all,
                                sty.group466
                              )}
                            >
                              <div
                                data-plasmic-name={"frame383"}
                                data-plasmic-override={overrides.frame383}
                                className={classNames(
                                  defaultcss.all,
                                  sty.frame383
                                )}
                              >
                                <div
                                  className={classNames(
                                    defaultcss.all,
                                    defaultcss.__wab_text,
                                    sty.box___26Uig
                                  )}
                                >
                                  {"698,20"}
                                </div>

                                <div
                                  className={classNames(
                                    defaultcss.all,
                                    defaultcss.__wab_text,
                                    sty.box__xfi83
                                  )}
                                >
                                  {"kWh"}
                                </div>
                              </div>

                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.box__eceSv
                                )}
                              >
                                {"Production"}
                              </div>
                            </div>
                          </div>
                        </div>

                        <div
                          data-plasmic-name={"group468"}
                          data-plasmic-override={overrides.group468}
                          className={classNames(defaultcss.all, sty.group468)}
                        >
                          <div
                            data-plasmic-name={"rectangle35"}
                            data-plasmic-override={overrides.rectangle35}
                            className={classNames(
                              defaultcss.all,
                              sty.rectangle35
                            )}
                          />

                          <div
                            data-plasmic-name={"group469"}
                            data-plasmic-override={overrides.group469}
                            className={classNames(defaultcss.all, sty.group469)}
                          >
                            <div
                              data-plasmic-name={"frame384"}
                              data-plasmic-override={overrides.frame384}
                              className={classNames(
                                defaultcss.all,
                                sty.frame384
                              )}
                            >
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.box__xrUz
                                )}
                              >
                                {"22,120"}
                              </div>

                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.box__u95E2
                                )}
                              >
                                {"h"}
                              </div>
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__mZ7Yq
                              )}
                            >
                              {"Yield"}
                            </div>
                          </div>

                          <div
                            data-plasmic-name={"group470"}
                            data-plasmic-override={overrides.group470}
                            className={classNames(defaultcss.all, sty.group470)}
                          >
                            <Ellipse4Icon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__uer2J
                              )}
                              role={"img"}
                            />

                            <IconOutlinesparklesIcon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__pJjgC
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </p.Stack>
                    </div>

                    <div
                      data-plasmic-name={"group472"}
                      data-plasmic-override={overrides.group472}
                      className={classNames(defaultcss.all, sty.group472)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame500"}
                        data-plasmic-override={overrides.frame500}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.frame500)}
                      >
                        <div
                          data-plasmic-name={"group473"}
                          data-plasmic-override={overrides.group473}
                          className={classNames(defaultcss.all, sty.group473)}
                        >
                          <div
                            data-plasmic-name={"rectangle36"}
                            data-plasmic-override={overrides.rectangle36}
                            className={classNames(
                              defaultcss.all,
                              sty.rectangle36
                            )}
                          />

                          <div
                            data-plasmic-name={"group499"}
                            data-plasmic-override={overrides.group499}
                            className={classNames(defaultcss.all, sty.group499)}
                          >
                            <div
                              data-plasmic-name={"group500"}
                              data-plasmic-override={overrides.group500}
                              className={classNames(
                                defaultcss.all,
                                sty.group500
                              )}
                            >
                              <Rectangle35Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__ajOBi
                                )}
                                role={"img"}
                              />

                              <div
                                data-plasmic-name={"group474"}
                                data-plasmic-override={overrides.group474}
                                className={classNames(
                                  defaultcss.all,
                                  sty.group474
                                )}
                              >
                                <IconOutlinelightningBoltIcon
                                  className={classNames(
                                    defaultcss.all,
                                    sty.svg__umbU
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>

                            <div
                              data-plasmic-name={"group475"}
                              data-plasmic-override={overrides.group475}
                              className={classNames(
                                defaultcss.all,
                                sty.group475
                              )}
                            >
                              <div
                                data-plasmic-name={"frame385"}
                                data-plasmic-override={overrides.frame385}
                                className={classNames(
                                  defaultcss.all,
                                  sty.frame385
                                )}
                              >
                                <div
                                  className={classNames(
                                    defaultcss.all,
                                    defaultcss.__wab_text,
                                    sty.box__kXt3L
                                  )}
                                >
                                  {"32.56"}
                                </div>

                                <div
                                  className={classNames(
                                    defaultcss.all,
                                    defaultcss.__wab_text,
                                    sty.box__zp1La
                                  )}
                                >
                                  {"%"}
                                </div>
                              </div>

                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.box__gmd3J
                                )}
                              >
                                {"Availability"}
                              </div>
                            </div>
                          </div>
                        </div>

                        <div
                          data-plasmic-name={"group476"}
                          data-plasmic-override={overrides.group476}
                          className={classNames(defaultcss.all, sty.group476)}
                        >
                          <div
                            data-plasmic-name={"rectangle39"}
                            data-plasmic-override={overrides.rectangle39}
                            className={classNames(
                              defaultcss.all,
                              sty.rectangle39
                            )}
                          />

                          <div
                            data-plasmic-name={"group477"}
                            data-plasmic-override={overrides.group477}
                            className={classNames(defaultcss.all, sty.group477)}
                          >
                            <div
                              data-plasmic-name={"frame386"}
                              data-plasmic-override={overrides.frame386}
                              className={classNames(
                                defaultcss.all,
                                sty.frame386
                              )}
                            >
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.box__obrka
                                )}
                              >
                                {"98,22"}
                              </div>

                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.box__dqPwB
                                )}
                              >
                                {"%"}
                              </div>
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__pgPlQ
                              )}
                            >
                              {"Performance"}
                            </div>
                          </div>

                          <div
                            data-plasmic-name={"group478"}
                            data-plasmic-override={overrides.group478}
                            className={classNames(defaultcss.all, sty.group478)}
                          >
                            <Ellipse4Icon
                              className={classNames(
                                defaultcss.all,
                                sty.svg___0Cyr7
                              )}
                              role={"img"}
                            />

                            <IconOutlinesparklesIcon
                              className={classNames(
                                defaultcss.all,
                                sty.svg___2Tapp
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </p.Stack>
                    </div>
                  </p.Stack>

                  <div
                    data-plasmic-name={"group464"}
                    data-plasmic-override={overrides.group464}
                    className={classNames(defaultcss.all, sty.group464)}
                  >
                    <div
                      data-plasmic-name={"rectangle26"}
                      data-plasmic-override={overrides.rectangle26}
                      className={classNames(defaultcss.all, sty.rectangle26)}
                    />

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame504"}
                      data-plasmic-override={overrides.frame504}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.frame504)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame502"}
                        data-plasmic-override={overrides.frame502}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.frame502)}
                      >
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame503"}
                          data-plasmic-override={overrides.frame503}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.frame503)}
                        >
                          <IconSolidsunIcon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__nT2Qz
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__o47Zg
                            )}
                          >
                            {"Irradiation:"}
                          </div>

                          <div
                            data-plasmic-name={"_282735Whm"}
                            data-plasmic-override={overrides._282735Whm}
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty._282735Whm
                            )}
                          >
                            {" 2827.35 Wh/m² "}
                          </div>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"frame505"}
                          data-plasmic-override={overrides.frame505}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.frame505)}
                        >
                          <IconSolidlightningBoltIcon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__zHMn0
                            )}
                            role={"img"}
                          />

                          <div
                            data-plasmic-name={"production"}
                            data-plasmic-override={overrides.production}
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.production
                            )}
                          >
                            {"Production: "}
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__pjUio
                            )}
                          >
                            {"50,2 kWh"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Line18Icon
                        className={classNames(defaultcss.all, sty.svg___7WuUg)}
                        role={"img"}
                      />

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"frame463"}
                        data-plasmic-override={overrides.frame463}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.frame463)}
                      >
                        <div
                          data-plasmic-name={"group456"}
                          data-plasmic-override={overrides.group456}
                          className={classNames(defaultcss.all, sty.group456)}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box___4IpL
                            )}
                          >
                            {"05/06"}
                          </div>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame501"}
                            data-plasmic-override={overrides.frame501}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.frame501)}
                          >
                            <div
                              data-plasmic-name={"rectangle28"}
                              data-plasmic-override={overrides.rectangle28}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle28
                              )}
                            />

                            <div
                              data-plasmic-name={"rectangle29"}
                              data-plasmic-override={overrides.rectangle29}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle29
                              )}
                            />
                          </p.Stack>
                        </div>

                        <div
                          data-plasmic-name={"group457"}
                          data-plasmic-override={overrides.group457}
                          className={classNames(defaultcss.all, sty.group457)}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box___0UmEj
                            )}
                          >
                            {"06/06"}
                          </div>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame506"}
                            data-plasmic-override={overrides.frame506}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.frame506)}
                          >
                            <div
                              data-plasmic-name={"rectangle30"}
                              data-plasmic-override={overrides.rectangle30}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle30
                              )}
                            />

                            <div
                              data-plasmic-name={"rectangle31"}
                              data-plasmic-override={overrides.rectangle31}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle31
                              )}
                            />
                          </p.Stack>
                        </div>

                        <div
                          data-plasmic-name={"group458"}
                          data-plasmic-override={overrides.group458}
                          className={classNames(defaultcss.all, sty.group458)}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__uowcx
                            )}
                          >
                            {"07/06"}
                          </div>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame507"}
                            data-plasmic-override={overrides.frame507}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.frame507)}
                          >
                            <div
                              data-plasmic-name={"rectangle32"}
                              data-plasmic-override={overrides.rectangle32}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle32
                              )}
                            />

                            <div
                              data-plasmic-name={"rectangle33"}
                              data-plasmic-override={overrides.rectangle33}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle33
                              )}
                            />
                          </p.Stack>
                        </div>

                        <div
                          data-plasmic-name={"group459"}
                          data-plasmic-override={overrides.group459}
                          className={classNames(defaultcss.all, sty.group459)}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__bbeX
                            )}
                          >
                            {"08/06"}
                          </div>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame508"}
                            data-plasmic-override={overrides.frame508}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.frame508)}
                          >
                            <div
                              data-plasmic-name={"rectangle40"}
                              data-plasmic-override={overrides.rectangle40}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle40
                              )}
                            />

                            <div
                              data-plasmic-name={"rectangle41"}
                              data-plasmic-override={overrides.rectangle41}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle41
                              )}
                            />
                          </p.Stack>
                        </div>

                        <div
                          data-plasmic-name={"group463"}
                          data-plasmic-override={overrides.group463}
                          className={classNames(defaultcss.all, sty.group463)}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__ncmvY
                            )}
                          >
                            {"09/06"}
                          </div>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame510"}
                            data-plasmic-override={overrides.frame510}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.frame510)}
                          >
                            <div
                              data-plasmic-name={"rectangle42"}
                              data-plasmic-override={overrides.rectangle42}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle42
                              )}
                            />

                            <div
                              data-plasmic-name={"rectangle43"}
                              data-plasmic-override={overrides.rectangle43}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle43
                              )}
                            />
                          </p.Stack>
                        </div>

                        <div
                          data-plasmic-name={"group479"}
                          data-plasmic-override={overrides.group479}
                          className={classNames(defaultcss.all, sty.group479)}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__jisFn
                            )}
                          >
                            {"10/06"}
                          </div>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame511"}
                            data-plasmic-override={overrides.frame511}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.frame511)}
                          >
                            <div
                              data-plasmic-name={"rectangle44"}
                              data-plasmic-override={overrides.rectangle44}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle44
                              )}
                            />

                            <div
                              data-plasmic-name={"rectangle45"}
                              data-plasmic-override={overrides.rectangle45}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle45
                              )}
                            />
                          </p.Stack>
                        </div>

                        <div
                          data-plasmic-name={"group462"}
                          data-plasmic-override={overrides.group462}
                          className={classNames(defaultcss.all, sty.group462)}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__ggO1J
                            )}
                          >
                            {"11/06"}
                          </div>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"frame512"}
                            data-plasmic-override={overrides.frame512}
                            hasGap={true}
                            className={classNames(defaultcss.all, sty.frame512)}
                          >
                            <div
                              data-plasmic-name={"rectangle46"}
                              data-plasmic-override={overrides.rectangle46}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle46
                              )}
                            />

                            <div
                              data-plasmic-name={"rectangle47"}
                              data-plasmic-override={overrides.rectangle47}
                              className={classNames(
                                defaultcss.all,
                                sty.rectangle47
                              )}
                            />
                          </p.Stack>
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </div>
                </p.Stack>
              </div>
            </p.Stack>

            <div
              data-plasmic-name={"group496"}
              data-plasmic-override={overrides.group496}
              className={classNames(defaultcss.all, sty.group496)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__llzNl
                )}
              >
                {"606-3727 Ullamcorper. Street"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__pqia6
                )}
              >
                {"Capacity: 3.91 kWp"}
              </div>
            </div>

            <div
              data-plasmic-name={"nativeStatusBar2"}
              data-plasmic-override={overrides.nativeStatusBar2}
              className={classNames(defaultcss.all, sty.nativeStatusBar2)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__yLsRd
                )}
              >
                {"9:41"}
              </div>

              <MobileSignalIcon
                className={classNames(defaultcss.all, sty.svg__eVi2)}
                role={"img"}
              />

              <WifiIcon
                className={classNames(defaultcss.all, sty.svg__hieVj)}
                role={"img"}
              />

              <div
                data-plasmic-name={"battery2"}
                data-plasmic-override={overrides.battery2}
                className={classNames(defaultcss.all, sty.battery2)}
              >
                <BatteryIcon
                  className={classNames(defaultcss.all, sty.svg__viAl)}
                  role={"img"}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "dashboardSiteDetail",
    "nativeStatusBar",
    "battery",
    "group439",
    "rectangle23",
    "image",
    "rectangle24",
    "barsNavBarsStandard",
    "group505",
    "title",
    "frame495",
    "group454",
    "rectangle5",
    "frame509",
    "maskGroup",
    "rectangle4",
    "group",
    "frame9",
    "sun1",
    "group2",
    "group3",
    "group4",
    "group5",
    "group6",
    "group7",
    "group8",
    "group9",
    "group10",
    "group453",
    "frame497",
    "frame2",
    "group455",
    "rectangle25",
    "frame453",
    "frame450",
    "frame451",
    "wh",
    "frame452",
    "frame454",
    "kWh",
    "frame455",
    "frame456",
    "group503",
    "rectangle37",
    "rectangle38",
    "frame10",
    "frame7",
    "group494",
    "frame498",
    "frame474",
    "group471",
    "frame499",
    "group467",
    "rectangle34",
    "group498",
    "group497",
    "group465",
    "group466",
    "frame383",
    "group468",
    "rectangle35",
    "group469",
    "frame384",
    "group470",
    "group472",
    "frame500",
    "group473",
    "rectangle36",
    "group499",
    "group500",
    "group474",
    "group475",
    "frame385",
    "group476",
    "rectangle39",
    "group477",
    "frame386",
    "group478",
    "group464",
    "rectangle26",
    "frame504",
    "frame502",
    "frame503",
    "_282735Whm",
    "frame505",
    "production",
    "frame463",
    "group456",
    "frame501",
    "rectangle28",
    "rectangle29",
    "group457",
    "frame506",
    "rectangle30",
    "rectangle31",
    "group458",
    "frame507",
    "rectangle32",
    "rectangle33",
    "group459",
    "frame508",
    "rectangle40",
    "rectangle41",
    "group463",
    "frame510",
    "rectangle42",
    "rectangle43",
    "group479",
    "frame511",
    "rectangle44",
    "rectangle45",
    "group462",
    "frame512",
    "rectangle46",
    "rectangle47",
    "group496",
    "nativeStatusBar2",
    "battery2"
  ],

  dashboardSiteDetail: [
    "dashboardSiteDetail",
    "nativeStatusBar",
    "battery",
    "group439",
    "rectangle23",
    "image",
    "rectangle24",
    "barsNavBarsStandard",
    "group505",
    "title",
    "frame495",
    "group454",
    "rectangle5",
    "frame509",
    "maskGroup",
    "rectangle4",
    "group",
    "frame9",
    "sun1",
    "group2",
    "group3",
    "group4",
    "group5",
    "group6",
    "group7",
    "group8",
    "group9",
    "group10",
    "group453",
    "frame497",
    "frame2",
    "group455",
    "rectangle25",
    "frame453",
    "frame450",
    "frame451",
    "wh",
    "frame452",
    "frame454",
    "kWh",
    "frame455",
    "frame456",
    "group503",
    "rectangle37",
    "rectangle38",
    "frame10",
    "frame7",
    "group494",
    "frame498",
    "frame474",
    "group471",
    "frame499",
    "group467",
    "rectangle34",
    "group498",
    "group497",
    "group465",
    "group466",
    "frame383",
    "group468",
    "rectangle35",
    "group469",
    "frame384",
    "group470",
    "group472",
    "frame500",
    "group473",
    "rectangle36",
    "group499",
    "group500",
    "group474",
    "group475",
    "frame385",
    "group476",
    "rectangle39",
    "group477",
    "frame386",
    "group478",
    "group464",
    "rectangle26",
    "frame504",
    "frame502",
    "frame503",
    "_282735Whm",
    "frame505",
    "production",
    "frame463",
    "group456",
    "frame501",
    "rectangle28",
    "rectangle29",
    "group457",
    "frame506",
    "rectangle30",
    "rectangle31",
    "group458",
    "frame507",
    "rectangle32",
    "rectangle33",
    "group459",
    "frame508",
    "rectangle40",
    "rectangle41",
    "group463",
    "frame510",
    "rectangle42",
    "rectangle43",
    "group479",
    "frame511",
    "rectangle44",
    "rectangle45",
    "group462",
    "frame512",
    "rectangle46",
    "rectangle47",
    "group496",
    "nativeStatusBar2",
    "battery2"
  ],

  nativeStatusBar: ["nativeStatusBar", "battery"],
  battery: ["battery"],
  group439: ["group439", "rectangle23", "image"],
  rectangle23: ["rectangle23"],
  image: ["image"],
  rectangle24: ["rectangle24"],
  barsNavBarsStandard: ["barsNavBarsStandard", "group505", "title"],
  group505: ["group505", "title"],
  title: ["title"],
  frame495: [
    "frame495",
    "group454",
    "rectangle5",
    "frame509",
    "maskGroup",
    "rectangle4",
    "group",
    "frame9",
    "sun1",
    "group2",
    "group3",
    "group4",
    "group5",
    "group6",
    "group7",
    "group8",
    "group9",
    "group10",
    "group453",
    "frame497",
    "frame2",
    "group455",
    "rectangle25",
    "frame453",
    "frame450",
    "frame451",
    "wh",
    "frame452",
    "frame454",
    "kWh",
    "frame455",
    "frame456",
    "group503",
    "rectangle37",
    "rectangle38",
    "frame10",
    "frame7",
    "group494",
    "frame498",
    "frame474",
    "group471",
    "frame499",
    "group467",
    "rectangle34",
    "group498",
    "group497",
    "group465",
    "group466",
    "frame383",
    "group468",
    "rectangle35",
    "group469",
    "frame384",
    "group470",
    "group472",
    "frame500",
    "group473",
    "rectangle36",
    "group499",
    "group500",
    "group474",
    "group475",
    "frame385",
    "group476",
    "rectangle39",
    "group477",
    "frame386",
    "group478",
    "group464",
    "rectangle26",
    "frame504",
    "frame502",
    "frame503",
    "_282735Whm",
    "frame505",
    "production",
    "frame463",
    "group456",
    "frame501",
    "rectangle28",
    "rectangle29",
    "group457",
    "frame506",
    "rectangle30",
    "rectangle31",
    "group458",
    "frame507",
    "rectangle32",
    "rectangle33",
    "group459",
    "frame508",
    "rectangle40",
    "rectangle41",
    "group463",
    "frame510",
    "rectangle42",
    "rectangle43",
    "group479",
    "frame511",
    "rectangle44",
    "rectangle45",
    "group462",
    "frame512",
    "rectangle46",
    "rectangle47"
  ],

  group454: [
    "group454",
    "rectangle5",
    "frame509",
    "maskGroup",
    "rectangle4",
    "group",
    "frame9",
    "sun1",
    "group2",
    "group3",
    "group4",
    "group5",
    "group6",
    "group7",
    "group8",
    "group9",
    "group10",
    "group453",
    "frame497",
    "frame2"
  ],

  rectangle5: ["rectangle5"],
  frame509: [
    "frame509",
    "maskGroup",
    "rectangle4",
    "group",
    "frame9",
    "sun1",
    "group2",
    "group3",
    "group4",
    "group5",
    "group6",
    "group7",
    "group8",
    "group9",
    "group10"
  ],

  maskGroup: ["maskGroup", "rectangle4", "group", "frame9"],
  rectangle4: ["rectangle4"],
  group: ["group", "frame9"],
  frame9: ["frame9"],
  sun1: [
    "sun1",
    "group2",
    "group3",
    "group4",
    "group5",
    "group6",
    "group7",
    "group8",
    "group9",
    "group10"
  ],

  group2: ["group2"],
  group3: ["group3"],
  group4: ["group4"],
  group5: ["group5"],
  group6: ["group6"],
  group7: ["group7"],
  group8: ["group8"],
  group9: ["group9"],
  group10: ["group10"],
  group453: ["group453", "frame497", "frame2"],
  frame497: ["frame497"],
  frame2: ["frame2"],
  group455: [
    "group455",
    "rectangle25",
    "frame453",
    "frame450",
    "frame451",
    "wh",
    "frame452",
    "frame454",
    "kWh",
    "frame455",
    "frame456"
  ],

  rectangle25: ["rectangle25"],
  frame453: [
    "frame453",
    "frame450",
    "frame451",
    "wh",
    "frame452",
    "frame454",
    "kWh",
    "frame455",
    "frame456"
  ],

  frame450: ["frame450", "frame451", "wh"],
  frame451: ["frame451", "wh"],
  wh: ["wh"],
  frame452: ["frame452", "frame454", "kWh"],
  frame454: ["frame454", "kWh"],
  kWh: ["kWh"],
  frame455: ["frame455", "frame456"],
  frame456: ["frame456"],
  group503: ["group503", "rectangle37", "rectangle38"],
  rectangle37: ["rectangle37"],
  rectangle38: ["rectangle38"],
  frame10: ["frame10", "frame7"],
  frame7: ["frame7"],
  group494: [
    "group494",
    "frame498",
    "frame474",
    "group471",
    "frame499",
    "group467",
    "rectangle34",
    "group498",
    "group497",
    "group465",
    "group466",
    "frame383",
    "group468",
    "rectangle35",
    "group469",
    "frame384",
    "group470",
    "group472",
    "frame500",
    "group473",
    "rectangle36",
    "group499",
    "group500",
    "group474",
    "group475",
    "frame385",
    "group476",
    "rectangle39",
    "group477",
    "frame386",
    "group478",
    "group464",
    "rectangle26",
    "frame504",
    "frame502",
    "frame503",
    "_282735Whm",
    "frame505",
    "production",
    "frame463",
    "group456",
    "frame501",
    "rectangle28",
    "rectangle29",
    "group457",
    "frame506",
    "rectangle30",
    "rectangle31",
    "group458",
    "frame507",
    "rectangle32",
    "rectangle33",
    "group459",
    "frame508",
    "rectangle40",
    "rectangle41",
    "group463",
    "frame510",
    "rectangle42",
    "rectangle43",
    "group479",
    "frame511",
    "rectangle44",
    "rectangle45",
    "group462",
    "frame512",
    "rectangle46",
    "rectangle47"
  ],

  frame498: [
    "frame498",
    "frame474",
    "group471",
    "frame499",
    "group467",
    "rectangle34",
    "group498",
    "group497",
    "group465",
    "group466",
    "frame383",
    "group468",
    "rectangle35",
    "group469",
    "frame384",
    "group470",
    "group472",
    "frame500",
    "group473",
    "rectangle36",
    "group499",
    "group500",
    "group474",
    "group475",
    "frame385",
    "group476",
    "rectangle39",
    "group477",
    "frame386",
    "group478",
    "group464",
    "rectangle26",
    "frame504",
    "frame502",
    "frame503",
    "_282735Whm",
    "frame505",
    "production",
    "frame463",
    "group456",
    "frame501",
    "rectangle28",
    "rectangle29",
    "group457",
    "frame506",
    "rectangle30",
    "rectangle31",
    "group458",
    "frame507",
    "rectangle32",
    "rectangle33",
    "group459",
    "frame508",
    "rectangle40",
    "rectangle41",
    "group463",
    "frame510",
    "rectangle42",
    "rectangle43",
    "group479",
    "frame511",
    "rectangle44",
    "rectangle45",
    "group462",
    "frame512",
    "rectangle46",
    "rectangle47"
  ],

  frame474: [
    "frame474",
    "group471",
    "frame499",
    "group467",
    "rectangle34",
    "group498",
    "group497",
    "group465",
    "group466",
    "frame383",
    "group468",
    "rectangle35",
    "group469",
    "frame384",
    "group470",
    "group472",
    "frame500",
    "group473",
    "rectangle36",
    "group499",
    "group500",
    "group474",
    "group475",
    "frame385",
    "group476",
    "rectangle39",
    "group477",
    "frame386",
    "group478"
  ],

  group471: [
    "group471",
    "frame499",
    "group467",
    "rectangle34",
    "group498",
    "group497",
    "group465",
    "group466",
    "frame383",
    "group468",
    "rectangle35",
    "group469",
    "frame384",
    "group470"
  ],

  frame499: [
    "frame499",
    "group467",
    "rectangle34",
    "group498",
    "group497",
    "group465",
    "group466",
    "frame383",
    "group468",
    "rectangle35",
    "group469",
    "frame384",
    "group470"
  ],

  group467: [
    "group467",
    "rectangle34",
    "group498",
    "group497",
    "group465",
    "group466",
    "frame383"
  ],

  rectangle34: ["rectangle34"],
  group498: ["group498", "group497", "group465", "group466", "frame383"],
  group497: ["group497", "group465"],
  group465: ["group465"],
  group466: ["group466", "frame383"],
  frame383: ["frame383"],
  group468: ["group468", "rectangle35", "group469", "frame384", "group470"],
  rectangle35: ["rectangle35"],
  group469: ["group469", "frame384"],
  frame384: ["frame384"],
  group470: ["group470"],
  group472: [
    "group472",
    "frame500",
    "group473",
    "rectangle36",
    "group499",
    "group500",
    "group474",
    "group475",
    "frame385",
    "group476",
    "rectangle39",
    "group477",
    "frame386",
    "group478"
  ],

  frame500: [
    "frame500",
    "group473",
    "rectangle36",
    "group499",
    "group500",
    "group474",
    "group475",
    "frame385",
    "group476",
    "rectangle39",
    "group477",
    "frame386",
    "group478"
  ],

  group473: [
    "group473",
    "rectangle36",
    "group499",
    "group500",
    "group474",
    "group475",
    "frame385"
  ],

  rectangle36: ["rectangle36"],
  group499: ["group499", "group500", "group474", "group475", "frame385"],
  group500: ["group500", "group474"],
  group474: ["group474"],
  group475: ["group475", "frame385"],
  frame385: ["frame385"],
  group476: ["group476", "rectangle39", "group477", "frame386", "group478"],
  rectangle39: ["rectangle39"],
  group477: ["group477", "frame386"],
  frame386: ["frame386"],
  group478: ["group478"],
  group464: [
    "group464",
    "rectangle26",
    "frame504",
    "frame502",
    "frame503",
    "_282735Whm",
    "frame505",
    "production",
    "frame463",
    "group456",
    "frame501",
    "rectangle28",
    "rectangle29",
    "group457",
    "frame506",
    "rectangle30",
    "rectangle31",
    "group458",
    "frame507",
    "rectangle32",
    "rectangle33",
    "group459",
    "frame508",
    "rectangle40",
    "rectangle41",
    "group463",
    "frame510",
    "rectangle42",
    "rectangle43",
    "group479",
    "frame511",
    "rectangle44",
    "rectangle45",
    "group462",
    "frame512",
    "rectangle46",
    "rectangle47"
  ],

  rectangle26: ["rectangle26"],
  frame504: [
    "frame504",
    "frame502",
    "frame503",
    "_282735Whm",
    "frame505",
    "production",
    "frame463",
    "group456",
    "frame501",
    "rectangle28",
    "rectangle29",
    "group457",
    "frame506",
    "rectangle30",
    "rectangle31",
    "group458",
    "frame507",
    "rectangle32",
    "rectangle33",
    "group459",
    "frame508",
    "rectangle40",
    "rectangle41",
    "group463",
    "frame510",
    "rectangle42",
    "rectangle43",
    "group479",
    "frame511",
    "rectangle44",
    "rectangle45",
    "group462",
    "frame512",
    "rectangle46",
    "rectangle47"
  ],

  frame502: ["frame502", "frame503", "_282735Whm", "frame505", "production"],
  frame503: ["frame503", "_282735Whm"],
  _282735Whm: ["_282735Whm"],
  frame505: ["frame505", "production"],
  production: ["production"],
  frame463: [
    "frame463",
    "group456",
    "frame501",
    "rectangle28",
    "rectangle29",
    "group457",
    "frame506",
    "rectangle30",
    "rectangle31",
    "group458",
    "frame507",
    "rectangle32",
    "rectangle33",
    "group459",
    "frame508",
    "rectangle40",
    "rectangle41",
    "group463",
    "frame510",
    "rectangle42",
    "rectangle43",
    "group479",
    "frame511",
    "rectangle44",
    "rectangle45",
    "group462",
    "frame512",
    "rectangle46",
    "rectangle47"
  ],

  group456: ["group456", "frame501", "rectangle28", "rectangle29"],
  frame501: ["frame501", "rectangle28", "rectangle29"],
  rectangle28: ["rectangle28"],
  rectangle29: ["rectangle29"],
  group457: ["group457", "frame506", "rectangle30", "rectangle31"],
  frame506: ["frame506", "rectangle30", "rectangle31"],
  rectangle30: ["rectangle30"],
  rectangle31: ["rectangle31"],
  group458: ["group458", "frame507", "rectangle32", "rectangle33"],
  frame507: ["frame507", "rectangle32", "rectangle33"],
  rectangle32: ["rectangle32"],
  rectangle33: ["rectangle33"],
  group459: ["group459", "frame508", "rectangle40", "rectangle41"],
  frame508: ["frame508", "rectangle40", "rectangle41"],
  rectangle40: ["rectangle40"],
  rectangle41: ["rectangle41"],
  group463: ["group463", "frame510", "rectangle42", "rectangle43"],
  frame510: ["frame510", "rectangle42", "rectangle43"],
  rectangle42: ["rectangle42"],
  rectangle43: ["rectangle43"],
  group479: ["group479", "frame511", "rectangle44", "rectangle45"],
  frame511: ["frame511", "rectangle44", "rectangle45"],
  rectangle44: ["rectangle44"],
  rectangle45: ["rectangle45"],
  group462: ["group462", "frame512", "rectangle46", "rectangle47"],
  frame512: ["frame512", "rectangle46", "rectangle47"],
  rectangle46: ["rectangle46"],
  rectangle47: ["rectangle47"],
  group496: ["group496"],
  nativeStatusBar2: ["nativeStatusBar2", "battery2"],
  battery2: ["battery2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dashboardSiteDetail: makeNodeComponent("dashboardSiteDetail"),
    nativeStatusBar: makeNodeComponent("nativeStatusBar"),
    battery: makeNodeComponent("battery"),
    group439: makeNodeComponent("group439"),
    rectangle23: makeNodeComponent("rectangle23"),
    image: makeNodeComponent("image"),
    rectangle24: makeNodeComponent("rectangle24"),
    barsNavBarsStandard: makeNodeComponent("barsNavBarsStandard"),
    group505: makeNodeComponent("group505"),
    title: makeNodeComponent("title"),
    frame495: makeNodeComponent("frame495"),
    group454: makeNodeComponent("group454"),
    rectangle5: makeNodeComponent("rectangle5"),
    frame509: makeNodeComponent("frame509"),
    maskGroup: makeNodeComponent("maskGroup"),
    rectangle4: makeNodeComponent("rectangle4"),
    group: makeNodeComponent("group"),
    frame9: makeNodeComponent("frame9"),
    sun1: makeNodeComponent("sun1"),
    group2: makeNodeComponent("group2"),
    group3: makeNodeComponent("group3"),
    group4: makeNodeComponent("group4"),
    group5: makeNodeComponent("group5"),
    group6: makeNodeComponent("group6"),
    group7: makeNodeComponent("group7"),
    group8: makeNodeComponent("group8"),
    group9: makeNodeComponent("group9"),
    group10: makeNodeComponent("group10"),
    group453: makeNodeComponent("group453"),
    frame497: makeNodeComponent("frame497"),
    frame2: makeNodeComponent("frame2"),
    group455: makeNodeComponent("group455"),
    rectangle25: makeNodeComponent("rectangle25"),
    frame453: makeNodeComponent("frame453"),
    frame450: makeNodeComponent("frame450"),
    frame451: makeNodeComponent("frame451"),
    wh: makeNodeComponent("wh"),
    frame452: makeNodeComponent("frame452"),
    frame454: makeNodeComponent("frame454"),
    kWh: makeNodeComponent("kWh"),
    frame455: makeNodeComponent("frame455"),
    frame456: makeNodeComponent("frame456"),
    group503: makeNodeComponent("group503"),
    rectangle37: makeNodeComponent("rectangle37"),
    rectangle38: makeNodeComponent("rectangle38"),
    frame10: makeNodeComponent("frame10"),
    frame7: makeNodeComponent("frame7"),
    group494: makeNodeComponent("group494"),
    frame498: makeNodeComponent("frame498"),
    frame474: makeNodeComponent("frame474"),
    group471: makeNodeComponent("group471"),
    frame499: makeNodeComponent("frame499"),
    group467: makeNodeComponent("group467"),
    rectangle34: makeNodeComponent("rectangle34"),
    group498: makeNodeComponent("group498"),
    group497: makeNodeComponent("group497"),
    group465: makeNodeComponent("group465"),
    group466: makeNodeComponent("group466"),
    frame383: makeNodeComponent("frame383"),
    group468: makeNodeComponent("group468"),
    rectangle35: makeNodeComponent("rectangle35"),
    group469: makeNodeComponent("group469"),
    frame384: makeNodeComponent("frame384"),
    group470: makeNodeComponent("group470"),
    group472: makeNodeComponent("group472"),
    frame500: makeNodeComponent("frame500"),
    group473: makeNodeComponent("group473"),
    rectangle36: makeNodeComponent("rectangle36"),
    group499: makeNodeComponent("group499"),
    group500: makeNodeComponent("group500"),
    group474: makeNodeComponent("group474"),
    group475: makeNodeComponent("group475"),
    frame385: makeNodeComponent("frame385"),
    group476: makeNodeComponent("group476"),
    rectangle39: makeNodeComponent("rectangle39"),
    group477: makeNodeComponent("group477"),
    frame386: makeNodeComponent("frame386"),
    group478: makeNodeComponent("group478"),
    group464: makeNodeComponent("group464"),
    rectangle26: makeNodeComponent("rectangle26"),
    frame504: makeNodeComponent("frame504"),
    frame502: makeNodeComponent("frame502"),
    frame503: makeNodeComponent("frame503"),
    _282735Whm: makeNodeComponent("_282735Whm"),
    frame505: makeNodeComponent("frame505"),
    production: makeNodeComponent("production"),
    frame463: makeNodeComponent("frame463"),
    group456: makeNodeComponent("group456"),
    frame501: makeNodeComponent("frame501"),
    rectangle28: makeNodeComponent("rectangle28"),
    rectangle29: makeNodeComponent("rectangle29"),
    group457: makeNodeComponent("group457"),
    frame506: makeNodeComponent("frame506"),
    rectangle30: makeNodeComponent("rectangle30"),
    rectangle31: makeNodeComponent("rectangle31"),
    group458: makeNodeComponent("group458"),
    frame507: makeNodeComponent("frame507"),
    rectangle32: makeNodeComponent("rectangle32"),
    rectangle33: makeNodeComponent("rectangle33"),
    group459: makeNodeComponent("group459"),
    frame508: makeNodeComponent("frame508"),
    rectangle40: makeNodeComponent("rectangle40"),
    rectangle41: makeNodeComponent("rectangle41"),
    group463: makeNodeComponent("group463"),
    frame510: makeNodeComponent("frame510"),
    rectangle42: makeNodeComponent("rectangle42"),
    rectangle43: makeNodeComponent("rectangle43"),
    group479: makeNodeComponent("group479"),
    frame511: makeNodeComponent("frame511"),
    rectangle44: makeNodeComponent("rectangle44"),
    rectangle45: makeNodeComponent("rectangle45"),
    group462: makeNodeComponent("group462"),
    frame512: makeNodeComponent("frame512"),
    rectangle46: makeNodeComponent("rectangle46"),
    rectangle47: makeNodeComponent("rectangle47"),
    group496: makeNodeComponent("group496"),
    nativeStatusBar2: makeNodeComponent("nativeStatusBar2"),
    battery2: makeNodeComponent("battery2"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
